CREATE TABLE USER_INFO( 
    USERID              VARCHAR2(10)            NOT NULL
  , PASSWORD            VARCHAR2(60)           NOT NULL
  , USERNAME            VARCHAR2(100)          NOT NULL
  , ROLE_NAME           VARCHAR2(10)           NOT NULL
  , LOGIN_FAILURE_COUNT NUMBER(10)   DEFAULT 0 NOT NULL
  , LOGIN_DENY_TIME     DATE
  , DELETED             NUMBER(1)    DEFAULT 0 NOT NULL
  , UPDATER_ID          VARCHAR2(10)
  , UPDATE_TIME         DATE
  , CREATER_ID          VARCHAR2(10)
  , CREATE_TIME         DATE
  , CONSTRAINT PK_USER_INFO PRIMARY KEY (USERID)
); 
